using System;
using RazorBladeGenerator;

namespace SampleApp
{
    [GenerateCode]
    public partial class Person
    {
        public string FirstName { get; set; } = string.Empty;
        public string LastName { get; set; } = string.Empty;
        public int Age { get; set; }
    }
    [GenerateCode]
    public partial class Person2
    {
        public string FirstName { get; set; } = string.Empty;
        public string LastName { get; set; } = string.Empty;
        public int Age { get; set; }
    }

    class Program
    {
        static void Main(string[] args)
        {
            var person = new Person
            {
                FirstName = "John",
                LastName = "Doe",
                Age = 30
            };

            // This method is generated by the source generator
            person.PrintProperties();

            // This method is also generated
            Console.WriteLine(person.ToString());
        }
    }
}

